<?php
/**
 * TL_ROOT/system/modules/cron/languages/de/tl_settings.php
 *
 * TYPOlight extension: cron 1.0.0 stable
 * Deutsch translation file
 *
 * Copyright : &copy; 2007, 2008, 2009
 * License   : GNU GPL V2
 * Author    : Peter Koch (acenes), http://ibk-software.com
 * Translator: Peter Koch (acenes), http://ibk-software.com
 *
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

$GLOBALS['TL_LANG']['tl_member']['civicrm_legend'] = "CiviCRM Integration";
$GLOBALS['TL_LANG']['tl_member']['civicrm_id']['0'] = "CiviCRM-ID";
$GLOBALS['TL_LANG']['tl_member']['civicrm_id']['1'] = "Wird vom System automatisch ermittelt.";
$GLOBALS['TL_LANG']['tl_member']['civicrm_sync'] = "CiviCRM-Abgleich";
$GLOBALS['TL_LANG']['tl_member']['civicrm_syncinfo'] = "Es wurden <strong>%d</strong> Kontakte mit CiviCRM synchronisiert.";
$GLOBALS['TL_LANG']['tl_member']['civicrm_nosync'] = "Es wurden <strong>keine</strong> Kontakte mit CiviCRM synchronisiert.";

?>
