<?php
/**
 * TL_ROOT/system/modules/cron/languages/de/tl_settings.php 
 * 
 * TYPOlight extension: cron 1.0.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2007, 2008, 2009 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Peter Koch (acenes), http://ibk-software.com 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['civicrm_legend'] = "CiviCRM Integration";
$GLOBALS['TL_LANG']['tl_settings']['civicrm_apiurl']['0'] = "URL zu CiviCRM";
$GLOBALS['TL_LANG']['tl_settings']['civicrm_apiurl']['1'] = "Geben Sie die URL zu CiviCRM an (zum Beispiel: \"https://www.my-domain.de/extern/\").";
$GLOBALS['TL_LANG']['tl_settings']['civicrm_sitekey']['0'] = "Site Key";
$GLOBALS['TL_LANG']['tl_settings']['civicrm_sitekey']['1'] = "Der geheime Site Key von CiviCRM. Der Key muss in \"standalone/civicrm.settings.php\" gesetzt werden.";
$GLOBALS['TL_LANG']['tl_settings']['civicrm_apikey']['0'] = "API Key";
$GLOBALS['TL_LANG']['tl_settings']['civicrm_apikey']['1'] = "Der benutzerspezifische geheime API-Key. Zur Zeit der Erstellung dieser Erweiterung muss er manuell in der CiviCRM-Datenbank in der Tabelle &lt;prefix&gt;_contact beim entsprechenden Benutzer erstellt werden.";
$GLOBALS['TL_LANG']['tl_settings']['civicrm_membergroup']['0'] = "Mitgliedergruppe";
$GLOBALS['TL_LANG']['tl_settings']['civicrm_membergroup']['1'] = "Mitglieder werden in CiviCRM dieser Gruppe zugewiesen. Geben Sie die nummerische ID an.";
 
?>
